### ISSUE TITLE
Intégration de Lotty (animations)

### ISSUE THREAD

**Issue by ieschalier** [kizeo/transiscope-mobile#3]

**Comment by agoqui** [comment]
https://docs.expo.io/versions/latest/sdk/lottie/ : J'adore :smile:

**Comment by agoqui** [comment]
Voici le loader transiscope fait par Yannis [LoaderTransicope](https://kizeo.slack.com/files/UH1N5L4LT/FKLTD5H17/data.json?fbclid=IwAR186rfADaCkcVAWnM6HWClTKmOj46_1yupbA7RNdhf_5-5fmSW2ScdkHVE)
Je vais essayer de l'inégrer aujourd'hui ou demain ;)
